### ISSUE TITLE
Query: What is the default PWM period in PXT

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1061]
microbit.org-ticket: 664

How do I work out how long the pulse is (both the whole pulse period and the actual length of the pulse high) on a Analog Write Pin? (say "Analog Write (100) to Pin P0") (as is used in the TechWillSaveUs roombot to control a PWM continuous servo?). No other instructions has been used prior to the call.

**Comment by pelikhan** [comment]
Please attach a code sample.

**Comment by bagofatoms** [comment]
First a few details - I was trying to explain to my son what is actually happening using the following two instructions (and only these two instructions) to control a TechWillSaveUs roombot style device which uses two continuous (and simple) PWM controlled servo's "Feetech FS90R". 

"analog write pin(P0, 100)"
"analog write pin(P1, 10)"

As per the TechWillSaveUs website. I asked TechWillSaveUs and have had no reply.  

Looking up the analog write pin instruction on the microbit website states some slightly misleading information (although I understand why it would be explained as so). It was stated for P0 as such:

"The following code writes the analog value specified ("100") to the P0 pin".  At first I thought it really wrote an analog value (i.e. voltage) to the pin, but after reading the FS90R spec it became apparent that it was actually a pulse being provided to P0 which effectively 'simulated' a voltage over the whole period.  The pxt website was even more confusing. In a hint it stated "Hint: When you tell it to write 256 (for example), this function does not really write 256. Instead, it writes a lot of different numbers, and their average is 256." 

I'm fairly sure that's not right too.  I think after much research that it is actually a pulse being written by  "Analog Write Pin" whose length to the whole pulse period is the same ratio as the analog write value specified (i.e. in this case "100") is to 1023 - i.e. a pulse about a 10th of the pulse period.  However, I don't have access to an oscilloscope to prove that and there are no details about the default pulse period.  

Hence my original question which whaleygeek helpfully reposted here. I just wanted to explain to my son how exactly the two simple instructions were making his roombot work with the two servos's used so he would understand why it works, and how the servos's are actually being controlled.

**Comment by pelikhan** [comment]
Under the hood, this C++ function is called: https://lancaster-university.github.io/microbit-docs/ubit/io/#setanalogvalue

**Comment by bagofatoms** [comment]
Again, lancaster university describe it as setting a level whereas I believe its actually setting a pulse as per my description, otherwise the servos's wouldn't work according to their specification as they rely on diff pulse widths for CW (when 1500～700 µsec) or CCW (when 1500～2300 µsec) as per the [datasheet](https://cdn-shop.adafruit.com/product-files/2442/FS90R-V2.0_specs.pdf) and not a level.  Setting a value of "100" or "10" for the Analog Write Pin instruction does change the direction of the servo.  hence, I would really like to know if this is true and most of all, what pulse length in ms a value of 1023 (or 1024) would be.  

The nearest explanation which I think seems most correct is on the micro python [website](http://microbit-micropython.readthedocs.io/en/latest/pin.html) for "write_analog(value):
Output a PWM signal on the pin, with the duty cycle proportional to the provided value. The value may be either an integer or a floating point number between 0 (0% duty cycle) and 1023 (100% duty)." 

But again, unfortunately, it doesn't state the ms length of a 100% duty cycle.  

If the micropython website is correct then most of the documentation for "analog write pin" on other websites such as microbit seems incorrect or misleading.

**Comment by pelikhan** [comment]
Have you tried setServoValue ? https://github.com/lancaster-university/microbit-dal/blob/5fa55812c7be1e428d9b255ca31b21cd66c72e4a/source/drivers/MicroBitPin.cpp#L248 ?

**Comment by bagofatoms** [comment]
The code my son is following is as directed by the TechWillSaveUs website for the bot he received at Xmas which uses the Analog Write Pin instructions.  It works, but my problem is (as a 'dad teacher' to a 10 year old) is to explain why and how.  The information I've found to date seems incorrect / misleading.  I sent support at TechWillSaveUs the above question about the pulse (and also asked why they didn't use, as you suggest, 'the servo instructions' such as setServoValue etc) which I would probably would have tried to use were I coding this from scratch having found them amongst all the documentation.  Perhaps its because the FEETECH servos are unusual in being continuous rotation servos, rather than the usual 0-180 type servo. I don't know - however, so far, the full answer about Analog Write Pin is still a mystery. If only I has a scope I could work it out!

**Comment by pelikhan** [comment]
They probably wrote their activity when we did not have yet the servo blocks. Content and tools were being built in parralel on the early days of the project.

**Comment by pelikhan** [comment]
For this kind of deeper dive answers, we would rather rely on the DAL documentation of setAnalogValue. The documentation should be updated there so that all editors using it benefit.

**Comment by abchatra** [comment]
Documentation update required in DAL. Not related to PXT.
