### ISSUE TITLE
Blocks feedback

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#1065]
microbit.org-ticket 519
(references blocks, but I think the UX is identical on PXT)

Ok. There are a few things about the GUI which I feel would make some tasks better and the software overall more usable. 

1) images > create image Fill the box. Don't use check boxes. Much easier to "draw" and imagine the image. The checkbox is already used in Show LEDs, and that's fine. 

2) need "stop running" button I started off a lesson with the poem "the night before xmas" preinstalled. And programming this in Block Editor made the work very laggy as I neard the end and a test of an animation, lead to the whole poem running while I was trying to work. [note, this is now implemented in PXT]

3) case for function encapsulation if there ever was a gateway to learning function encapsulation it must be animations in a poem. I want easy reuse. 

4) major slowdown My laptop's fan is full power and the screen is terribly slow. Is it the size (see pic) or that the program is running? that's all for now

**Comment by abchatra** [comment]
_major slowdown My laptop's fan is full power and the screen is terribly slow. Is it the size (see pic)_ 

Can you please share the pic?

**Comment by DavidWhaleIET** [comment]
![image](https://cloud.githubusercontent.com/assets/16867446/21823717/4a513e60-d774-11e6-9ebf-4297216097ef.jpeg)

**Comment by DavidWhaleIET** [comment]
This is specifically in blocks, I know. The user tried in both blocks and in PXT and was having similar issues.

**Comment by jaustin** [comment]
I find CPU usage in Firefox is really high when the simulator is enabled. Even for a simple program (say, this, which makes it worse by bringing a second micro:bit in even though the radio is never 'used') 
<img width="281" alt="image" src="https://cloud.githubusercontent.com/assets/147113/21827737/d63ef3c6-d784-11e6-9f9a-0339ef826bc1.png">

It does seem to intelligently know when it's no longer the frontmost tab in Firefox, and calm down a bit, but it doesn't detect when Firefox is no longer the focussed window.

For example, I get Firefox Web Content eating 80-90% of a core when I have PXT visible or the frontmost tab, and ~10% otherwise. Chrome seems to be better.

**Comment by abchatra** [comment]
@jaustin Is your issue related to the original issue? From the screenshot original issue seems to be on chrome

**Comment by pelikhan** [comment]
@whaleygeek  The original screenshot refers to the microbit.co.uk block editor, which is not based on PXT.
@jaustin please open new issue for PXT issues.

**Comment by jaustin** [comment]
No problem, #1076 for the the new issue
