### ISSUE TITLE
need way to discover default value for optional argument

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#109]
the title says it all - can you put the default value into the intellisense?

**Comment by mmoskal** [comment]
Related to #50

**Comment by thomasdenney** [comment]
It would be nice if a function with optional parameters that are actually filled in JS could still be represented in some way in Blocks. For example, you get the 'cannot convert program' error if you write the following JavaScript:

```javascript
basic.showLeds(`
    . . . . .
    . . . . .
    . . # . .
    . . . . .
    . . . . .
    `, 0);
```

Alternatively, the block could still be shown, but with the extra parameter hidden in blocks.

**Comment by microsoftsam** [comment]
Since 1e5fd39f5e7b0c0ca16fa819412732d68887bc24 we now have support to add the default value (from jsdoc) into the intellisense auto completion. 
However, we currently don't insert optional parameters. 

If we wanted to add optional parameters we risk most of them not converting back into blocks. Thoughts?

**Comment by pelikhan** [comment]
Don't add the optional arguments. They are optional for a reason and meant for more advanced users.

**Comment by mmoskal** [comment]
<img width="518" alt="screen shot 2016-09-06 at 09 50 49" src="https://cloud.githubusercontent.com/assets/10673976/18267557/7cdae8d8-7417-11e6-9e6b-17cf8346f2f1.png">

In the screenshot above we don't show the default value of interval. The value is provided in the //% annotations (`//% parts="ledmatrix" interval.defl=150 shim=basic::showString`). Maybe it's possible to instead of:
```
function showString(text: string, interval?: number)
```
say in the tooltip:
```
function showString(text: string, interval: number = 150)
```

**Comment by abchatra** [comment]
Closing old issues. If this is still an issue please reopen.
