### ISSUE TITLE
Only image literals supported here

### ISSUE THREAD

**Issue by githubhero** [Microsoft/pxt#1170]
One question.

I have a little array of "leds":

```
var myLeds =[`
    . . . . .
    . # # # .
    . # # # .
    . # # # .
    . . . . .
    `, `
    # # # # #
    # # # # #
    # # # # #
    # # # # #
    # # # # #
    `, `
    . . . # .
    # . # . #
    . # # # .
    # . # . #
    . . . # .
    `];
```

I extract a random number this way:
`var randomNumber = Math.random(3);`

then this line follows: 
```
basic.showLeds(myLeds[randomNumber]);
```

but it throws an error ("only image literals supported here").

Why?

I tried passing a simple variable and it works.

```
// this is ok
var myLed = `
    # # # # #
    # # # # #
    # # # # #
    # # # # #
    # # # # #
    `;
basic.showLeds(myLed);
```

How am I supposed to do what I'm trying to do?   :-)

**Comment by pelikhan** [comment]
This compiler looses the information that the array contains string liberals abd complains. I would recommend to create a Image[] instead of string[].

**Comment by githubhero** [comment]
Hi @pelikhan, if you are suggesting to modify my array this way:

```
var myLeds = [images.createImage(`
    . . . . .
    . # # # .
    . # # # .
    . # # # .
    . . . . .
    `), images.createImage(`
    # # # # #
    # # # # #
    # # # # #
    # # # # #
    # # # # #
    `), images.createImage(`
    . . . # .
    # . # . #
    . # # # .
    # . # . #
    . . . # .
    `)];
```

it doesn't work (I get "Argument of type 'Image' is not assignable to parameter of type 'string'").

**Comment by pelikhan** [comment]
You should be able to create a single image as a long string and use plotFrame to display a particular frame of the picture.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by githubhero** [comment]
Ok, @pelikhan, anything went fine, thanks.   :-)

**Comment by riknoll** [comment]
Three solutions here:

1. Stop special-casing image literals and do the parsing on the device
2. Have two implementations of `showLeds`, one that takes the compiled images and one that takes a string and have the compiler call the second when it can't determine if the arguments were compiled or not
3. Figure out a different API that is human-readable but doesn't require parsing and deprecate `showLeds` (but keep the block the same)

I guess I'm leaning towards option 2, since 90% of the time the images will get precompiled like they are today. That would require us to do some control-flow analysis in the emitter though. 

For option 3, we could always do the classic array of numbers:

```
basic.showLeds([
  0,0,0,0,0,
  0,1,0,1,0,
  0,0,0,0,0,
  1,0,0,0,1,
  0,1,1,1,0
])
```

Maybe there is a more legible number combo than 0 and 1?

**Comment by riknoll** [comment]
I definitely don't like the current behavior, as it seems that only directly passing string literals works. The current implementation is basically adding a feature to typescript so we are no longer a subset.

**Comment by pelikhan** [comment]
Image liberals are compiled into byte arrays in flash which reduces memory pressure.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by pelikhan** [comment]
This is not a P1.
