### ISSUE TITLE
Blockly Search hangs UI

### ISSUE THREAD

**Issue by microsoftsam** [Microsoft/pxt#1237]
The Blockly search should complete everything in the web worker and not hang the UI. 

Comparing the beta and release channel, there's a significant decrease in the speed of search, but most importantly search in the beta channel is hanging the UI.

**Comment by riknoll** [comment]
Been fiddling with this and I still get the lag even if I cache all the nodes upfront (i.e. no query selectors or cloning on the UI thread). I did some performance profiling and it seems like the UI thread blocking is being caused by Blockly updating the toolbox. It's easier to see in Edge than in Chrome, but the UI stutter was definitely present before my changes. Discussed with @abchatra and I think the best solution is to just increase the debounce time so that it doesn't affect typing. I'll push my node caching changes as well since they might provide a slight improvement and take it back to what it used to be at.

**Comment by pelikhan** [comment]
Sounds good.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
