### ISSUE TITLE
Shadow blocks are not used when converting from JS

### ISSUE THREAD

**Issue by thomasdenney** [Microsoft/pxt#131]
If you add a block that uses shadow blocks (e.g. the `logic_compare` block) you cannot remove the operands. However, if you enter equivalent JS (e.g. `0 == 0`) and convert to blocks it will produce a block that doesn't use shadow values, and you can therefore remove the operands.

**Comment by riknoll** [comment]
This issue isn't limited to code in JS, it can also happen if you write some code in the blocks and then do a round trip. A picture of what that looks like:

![shadow_bug](https://cloud.githubusercontent.com/assets/13754588/18853096/56d71ef4-83f8-11e6-9a0d-fa81935e26c7.PNG)

The upper string literal is a shadow block that has not gone through the roundtrip, the second block has gone through the roundtrip and the string literal transformed into a real block. Especially weird because we don't currently allow the user to create string literal blocks!
