### ISSUE TITLE
handling of void-type variables is inconsistent

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#162]
![image](https://cloud.githubusercontent.com/assets/10767146/17116355/6fabc42e-5285-11e6-8718-2630a074a90d.png)

**Comment by thomasdenney** [comment]
1. [If a variable is not used, it is not type checked](https://github.com/Microsoft/pxt/blob/master/pxtlib/emitter/emitter.ts#L1723)
2. [A variable is used if its initializer has side effects](https://github.com/Microsoft/pxt/blob/master/pxtlib/emitter/emitter.ts#L811)
3. [Only the initializers of false, true, null, a number, or a string](https://github.com/Microsoft/pxt/blob/master/pxtlib/emitter/emitter.ts#L120) do not have side effects

`y` and `z` are therefore not type checked in the above because they are never used. If you add extra lines like `let a = y` or `let a = z` then you get the void-type error. `x` is 'used' because `undefined` 'has side effects' when used in the initialization. Interestingly, `undefined` is not a JS keyword, but a global variable that *is* undefined, so this actually needs further handling.

@mmoskal Type checking all variables, regardless of whether they are used, should fix this.

**Comment by mmoskal** [comment]
Thank you for fixing this! I guess we should either outlaw `undefined` or add some special handling.
