### ISSUE TITLE
Delete Project doesn't

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#1622]
Repro - Settings menu, Delete Project
Result - Opens the Project dialog, doesn't delete the current project

**Comment by microsoftsam** [comment]
I think this is more of a design issue. 
Today deleting a project, marks it as deleted, and brings up the Projects dialog. I guess the thought here is to give you a "what's next" sort of experience. If you click anywhere outside the window, you are still able to get back to your project (ie: its not deleted that way). 
The issue here is we don't have a landing "Welcome" experience, so if you delete a project, we have nothing to show, and hence we bring up the projects dialog.
I propose we just disable clicking anywhere outside that dialog when we are deleting a project. 
@pelikhan @Jaqster

**Comment by pelikhan** [comment]
Sounds good.

**Comment by Jaqster** [comment]
"disable clicking anywhere outside that dialog" -- I don't understand what you mean...?

**Comment by abchatra** [comment]
Wont' fix
