### ISSUE TITLE
discuss Static TypeScript design

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#1638]
Starting a thread to discuss what Static TypeScript is and is not. See https://github.com/Microsoft/pxt/blob/master/common-docs/javascript/sts.md

**Comment by mmoskal** [comment]
We do in fact support type assertions for class types. We could support union and intersection types between object values. What we cannot do is distinguish between strings, numbers, booleans and classes, since they all share representation. This is similar to Java, where `int` is different from `Int`, and you can cast `Int` to `Object` but not `int` to `Object`. C# hides that, while C++ doesn't really have the concept.

**Comment by tballmsft** [comment]
We just emit the underlying expression of the type assert. There is no runtime check of class, as we don't have a runtime tag.  We should make a decision on whether we want to add a runtime tag for classes. This will further distinguish them from records.   This would also allow us to check safety of downcasts.  Regarding union and intersection, once we have a runtime tag, they are easier to check.

**Comment by pelikhan** [comment]
Reads great :)

Need to address exceptions, floating point vs integer semantics, regex, debugging, async!!!.

We do support "any" for built in functions like string concat.

It would be good to give the historical context behind sts, it helps putting design decision in the context of microcontrollers.

**Comment by mmoskal** [comment]
@tballmsft  Sorry, that's right! I thought I implemented the tags. It shouldn't be too hard though. I think we should have it.  `instanceof` expression is only for classes, not for records, so we should be good there.

**Comment by tballmsft** [comment]
I am closing this issue and moving discussion to a pull request.
