### ISSUE TITLE
background block no longer able to be attached to a previous block

### ISSUE THREAD

**Issue by gingemonster** [Microsoft/pxt#2005]
It used to be possible to attach a "background" block to a previous code block, for example a button event, so that you could run two sequences at once.

A common requirement for this functionality is for a button press to both display a message and play some music as per https://www.youtube.com/watch?v=Y32FhgOVZnM

At the moment this cannot be easily done because the music will wait until the text has finished displaying, Only way to do it not would be a much more complicated background loop checking the state of a variable.

Please can we look at button back this ability

Thanks

**Comment by pelikhan** [comment]
control.runInBackground should not be treated as an event and but as a regular statement.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by DavidWhaleMEF** [comment]
Was this a typo @pelikhan ? There is no control.runInBackground in the current live build?

![screen shot 2017-04-30 at 21 59 16](https://cloud.githubusercontent.com/assets/25079586/25567948/5562ad70-2df0-11e7-9c42-500536b8de4a.png)

There is control.inBackground, but if you go into javascript mode and put that inside a button event handler, when you go back to blocks it takes it out again.

So, what would the code look like in this case, to press a button and then start a piece of music and scroll some text at the same time?

**Comment by DavidWhaleMEF** [comment]
You can start a melody, is this non blocking? If so, providing that the user can slot their own melody into this block that would solve the issue:

![screen shot 2017-04-30 at 22 02 06](https://cloud.githubusercontent.com/assets/25079586/25567978/ba43544c-2df0-11e7-9a02-12e4916f507b.png)


I also see that inside music.ts you do use control.inBackground to run a background melody.

```
    control.inBackground(() => {
                while (currentMelody.hasNextNote()) {
                    playNextNote(currentMelody);
                    if (!currentMelody.hasNextNote() && currentBackgroundMelody) {
                        // Swap the background melody back
                        currentMelody = currentBackgroundMelody;
                        currentBackgroundMelody = null;
                    }
                }
                currentMelody = null;
            })
```

So the issue that Brian is raising is a UX issue - the background block can't be used as a normal statement if going into blocks mode, because the visual scaffolding around it removes it from an event handler.

But I *think* in this case, @gingemonster , you can do what you want by just starting a melody and then scrolling the text (both in the button event handler) as starting a melody uses code that actually kicks this off in the background, so you don't actually need to use the background block (and therefore the problem goes away?)

**Comment by DavidWhaleMEF** [comment]
But @pelikhan Is there a reason why the background block has that visual style, if it is *not* an event handler?? It's because it has that shape that users can no longer put it inside an event handler (i.e. when the javascript round-trips back to blocks, it actually changes your program for you, rather than faithfully representing it)

I'm also a little concerned here that changing users javascript to something *different* when you round trip back to blocks, will penalise users who have mostly migrated to javascript but occassionally switch to blocks?

**Comment by pelikhan** [comment]
control.inBackround should not be treated as a event but as a statement. Then all would be solved.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by abchatra** [comment]
Fix here is to treat control.inBackground as a statement instead of event.

**Comment by DavidWhaleMEF** [comment]
Thanks guys.

**Comment by gingemonster** [comment]
thanks for looking at everybody

**Comment by abchatra** [comment]
This is fixed? If not please let me know. I will reopen in pxt-microbit repo.

**Comment by gingemonster** [comment]
If it is fixed it doesn't appear to be live on https://makecode.microbit.org/ I still cant join run-in-background to a code block

**Comment by abchatra** [comment]
Try alpha https://makecode.microbit.org/alpha#editor
