### ISSUE TITLE
pxt.microbit.org simulator eats 60% CPU

### ISSUE THREAD

**Issue by mmoskal** [Microsoft/pxt#2029]
On a high-end MacBook Pro, using Chrome, the simulator when running for example showString in a loop eats about 60% of a single core. Stoping and hiding the simulator fixes the problem.

**Comment by mmoskal** [comment]
This issue is still there, unlike #2028

**Comment by abchatra** [comment]
@mmoskal still an issue?

**Comment by mmoskal** [comment]
It looks it's down to 40% or so now. Not sure if because of some code changes, Chrome changes, or randomness. Some of it is system code (rendering?).

**Comment by Geoffree3** [comment]
Since migrating to the new JavaScript Blocks editor I've noticed the fans on my MacBook running full speed (normally you can't hear them).  Looking at the CPU usage, it's almost at 100% and this does not change when the simulator is stopped. This was using Opera browser.  I check on Safari and Chrome and they show about 35% CPU, which increase to about 70% when full screen micro:bit display.
This CPU usage is excessive given the application is just not doing much most of the time, even when simulating. Very little calculations involved or graphic calls.  I guess it's refreshing the display unnecessarily. Perhaps someone could take a look at this, to avoid this overheating!

**Comment by pelikhan** [comment]
What script are you running?

**Comment by Geoffree3** [comment]
Empty script.  Just micro:bit on screen -> 101% CPU load.  Opera browser.

**Comment by abchatra** [comment]
The microbit issues have moved to https://github.com/Microsoft/pxt-microbit repo. 
If this is still an issue please open the issue in that repo or let us know, we will reopen in that repo.
