### ISSUE TITLE
Resource fetch failed (typescript.js)

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2229]
microbit.org-ticket: 1945

When our schools are trying to access the pxt.microbit.org website they are getting an error in Chrome which says: Application Cache Error event: Resource fetch failed (2) https://pxt.azureedge.net/blob/0492ac1eb98fc8eaf9cb5086fd8c2cc9ee30ee48/typescript.js
We are using a web proxy and I've added the URL's here: https://pxt.microbit.org/faq to the Whitelist but we are still getting the error.
Can you please help

**Comment by abchatra** [comment]
@pelikhan any idea what is going wrong here?

**Comment by pelikhan** [comment]
Did it ever worked or did it start to fail? Is it failing for all computers or just one? Are there other browsers on the machine to test out?

**Comment by PragmaticPhil** [comment]
Customer has reported that this issue is now resolved:

"Yes there appears to have been some massive movement with the URLs that are being access when using the MicroBit service. In the end to resolve this issue we had the add the URLs at https://pxt.microbit.org/faq to the bypass list for the proxy server giving them unauthenticated access to the internet. The website is now working for us so the GitHub issue can be closed"

I do not have the widget to close this ticket, but am happy for it to be closed.
