### ISSUE TITLE
how to support more basic types in TypeScript

### ISSUE THREAD

**Issue by thomasjball** [Microsoft/pxt#228]
Since we are looking at compiling for microcontrollers, we really need a story for byte, short, etc. as well as float.

**Comment by mmoskal** [comment]
I think it wouldn't be difficult to introduce types (some bogus interfaces), but the problem is treating number literals as values of these types and operator overloading. For example, C has all sorts of rules about promotion of types.

We could support some storage attributes on globals and fields of objects. This may be enough for ARM, but for AVR you are probably also concerned about the size of locals on the stack.

Also, storage attributes wouldn't solve the problem with floats.

It would be good to get some input from the TypeScript people. I expect them to be not so warm about this idea, as it doesn't make much sense in JS and is rather complicated.

**Comment by tballmsft** [comment]
thanks, Michal.  Even for ARM and micro:bit, we have the problem of distinguishing ints from floats.

**Comment by tballmsft** [comment]
Thanks, @mmoskal
