### ISSUE TITLE
Infection game does not seem to translate well into blocks

### ISSUE THREAD

**Issue by fizban99** [Microsoft/pxt#2340]
I am taking a look at the infection game but I guess is one example of code that cannot be converted into blocks. I get an error if I try to see the Blocks equivalent. I thought that everything could be converted, although some things would become grey blocks... There seems to be exceptions, though... If that is the case,  it would be nice to get a warning either in the infection project page or in the pxt editor itself... https://pxt.microbit.org/projects/infection

**Comment by riknoll** [comment]
This is an issue with the block compilation; looks like we are not inferring the type of the "players" variable correctly; it's being initialized to a string rather than an array.

**Comment by riknoll** [comment]
Deferring to https://github.com/Microsoft/pxt/issues/2349 which has a better repro

**Comment by microbit-mark** [comment]
micro:bit-support:4078
@riknoll @pelikhan @abchatra Have another support ticket about this. The code still does not convert to blocks, 

https://makecode.microbit.org/94575-30587-68669-98014

though following this ticket through it looks like the underlying issue was resolved.

As with original request here, the[ docs](https://makecode.microbit.org/projects/infection) should be updated if this project can only run from Javascript
