### ISSUE TITLE
Side doc appear as collapsed instead of opened in IE

### ISSUE THREAD

**Issue by veler** [Microsoft/pxt#2406]
Under IE, when we open the help, the side doc appear as collapsed.

**Expected :**
- In IE, go to makecode.microbit.org
- Go to the help menu, click on Reference
- The side doc opens with the Reference page.

**Current situation :** 
- In IE, go to makecode.microbit.org
- Go to the help menu, click on Reference
- The side doc appear as collapsed, so we don't see the documentation first. We have to click on the Expand button.

**Comment by microsoftsam** [comment]
This has historically been by design. IE and mobile are considered as in "light mode", and in order to keep the page performant we open them up and keep it collapsed waiting for the user to indicate they want to open it. 

It makes sense to keep it this way for the initial load, but not when the user opens a page from the help menu (as they have expressed interest in seeing the page at that point)

**Comment by abchatra** [comment]
@veler feel free to fix.
