### ISSUE TITLE
TechWillSaveUs Phone-Bot makecode program crash

### ISSUE THREAD

**Issue by HyperDuino** [Microsoft/pxt#2425]
On this page:

https://make.techwillsaveus.com/bbc-microbit/activities/microbot-bluetooth-control

Step 1, "Code the Bot", "Launch Editor" opens this program:

https://makecode.microbit.org/33215-57699-87157-67857

The downloaded hex code, when paired and then interacted with either Bitty Software Android Game Controller (https://play.google.com/store/apps/details?id=com.bittysoftware.bittygamectrlr ) or Bitty Software Android micro:bit Blue (https://play.google.com/store/apps/details?id=com.bluetooth.mwoolley.microbitbledemo), crashes the Micro:Bit device (sad face on LEDs, "020" displayed, and/or random LED display pattern) if the buttons of the left-side controller of either Android app are pressed rapidly 4+ times.

[microbit-Micro-bot-phone-controller.hex.zip](https://github.com/Microsoft/pxt/files/1135988/microbit-Micro-bot-phone-controller.hex.zip)

**Comment by abchatra** [comment]
@riknoll Take a quick peep if you got some cycles.

**Comment by riknoll** [comment]
Error code 020 means out of memory. If I had to guess, I would say the issue here is that pressing the button rapidly is causing multiple fibers to spawn which is a bad idea since the Bluetooth stack takes up a lot of memory already. @finneyj thoughts?

**Comment by HyperDuino** [comment]
Students/kids aren't going to know (or want) to press control buttons on a game controller "slowly".

However, Hex/Block Code is on this page: https://www.kitronik.co.uk/blog/part-6-coding-with-the-pxt-editor

With this link: https://www.kitronik.co.uk/zip/microbit-Robot-Wars-Buggy-Code.zip (252,000 bytes) (Unzipped:  605,577 bytes)

opens in https://makecode.microbit.org/ editor, and when compiled and downloaded, works with the Bitty Software Game Controller, regardless of how fast/often the controls are touched.  

What's the key difference in the two block code program structures that causes the problem?

**Comment by riknoll** [comment]
Hmmm.... My best guess is the showLeds block is the culprit. The second example has 100% synchronous code in the event handler but in the first example the showLeds block is actually an asynchronous function because it has an implicit delay.  It's probably causing more fibers to pile up; that's just a guess though

**Comment by finneyj** [comment]
Hi Guys

Totally agree - kids need the ability to mash buttons at infeasible high rates. That's certainly the first thing my kids would do. :-)

@riknoll  I think you're on the right lines. An 020 panic is indeed out of heap memory, and with BLE enabled memory is really tight on the micro:bit (the Nordic stack takes about 11-12K of the 16K we have available). 

If you call a blocking operation (and I seem to recall showLeds is blocking because it delays for half a second or so after showing the image), then he runtime will spawn off a fiber to handle it, which will cost about 200 bytes. It will create a maximum of one fiber per event handler. Additionally, if you have event handlers containing a blocking call, any subsequent that can't be serviced will start to queue up on a per event handler basis, to a maximum that's defined at compile time (default 10 per event handler - https://github.com/lancaster-university/microbit-dal/blob/master/inc/core/MicroBitConfig.h#L165). Each event in the queue will add a bit more memory (only 20 byte or so, but it all adds up when we're running on fumes with BLE).

@HyperDuino Looking at your code (thanks for sharing!) I think I can see a few ways to reduce your memory footprint.

1) You could replace the showLeds with a "show image". I *think* this was a non-blocking call (right @riknoll ?) I expect this would greatly reduce queuing and therefore memory use. I'd definitely give this a try.

2) As we queue events per event handler, and many of your event handlers here are linked to the same source component (MES_DPAD_CONROLLER_ID), you could use a single event handler and an if/switch statement to then select the event code. This would also reduce the overhead. 

Hope this helps?

**Comment by abchatra** [comment]
There is no action on us, closing.

**Comment by jaustin** [comment]
@finneyj now we have our own heap allocator, couldn't we optionally start dropping events from the queue rather than OOM-ing? It's hard to reason about what the 'right' thing to do is (in some cases, it's clearly better to get an OOM than it is to silently drop packets) but there are two things that would really help here:
1) As well as having a queue length per event (and that means two queues per human-considered event in reality, as we have the up and down event), could we introduce a total number of queued events? At the moment it looks like your queue accounting is done on the fly (on a per queue basis) but could we add, for example, a global total queue count that we atomically increment/decrement when queueing things? 
2) Should we have shorter compile-time queue lengths when BLE is enabled versus disabled?

**Comment by finneyj** [comment]
@jaustin 

Yes, I've been idly pondering what the best thing to do is here. I think a range of things we could do here, but we also need to take care not to throw the baby out with the bathwater, and constrain behaviour for the general case due to what happens when we are very short of memory like this under BLE. I don't think we want to constrain how users create async event handler like this - it's a key part of the MakeCode experience IMHO...

So this leaves us with mechanisms that are transparent to the user (at least at the MakeCode level of the stack).

- Setting a global maximum queue length for events might be a good idea. I suspect it's not really the total number of events that's killing us here (although that doesn't help, and . It's the fact that a each of those event handlers could have their own thread stack, due to them having a blocking call inside (we already optimize out cases where event handlers are non blocking - they have no memory overhead).

- Reducing queue length would help under BLE, but as above, I suspect isn't the dominating factor.

- we *could* transparently route all MakeCode event handlers through a single catch all event handler on a per component basis. This would then effectively serialize all events from that component (in this case the MES_DPAD_CONTROLLER). Note this is a common pattern where a lot of event handlers are created (see TWSU sample above). This would mean some subtle change in semantics though - as event multiple handlers from the same component will suddenly start to feel a bit "different" from others. Not sure I like that.

thoughts?

**Comment by HyperDuino** [comment]
@finneyj @jaustin Thanks for continuing thinking about this.  I have some developer background, but I'm looking at this totally as the user experience level, in particular the teacher with a room of 30 students asking why the code doesn't work.  I recognize the challenges, and want to take the opportunity to say that overall I'm very impressed with the MakeCode+Micro:Bit experience.  Want to avoid having the MakeCode/MicroBit baby thrown out by a user because of the event-handling bathwater. :)

**Comment by finneyj** [comment]
:) indeed, I agree! Always a problem at bathtime... 

I'm actually very pragmatic about this... But having said that, we actually spent quite a lot of time tuning the semantics around event handling to be as intuitive to kids as possible. We essentially have a very scratch like threading model that kids know and love. All i'm saying is that we need to be careful not to swap one problem for another...

**Comment by finneyj** [comment]
hmm.... wonders if we could intelligently limit the number of concurrently running fibers based on the amount of available RAM...  in other words, don't ever try to execute more than "n" event handlers at once...

This could lead to some slightly odd behaviour if you have long running event handlers. "Why didn't that block work when the other one did?" "oh it just did work... but that took ages to happen... etc."

In most cases it's probably not noticeable though, and certainly less invasive than an OOM panic...

**Comment by HyperDuino** [comment]
@finneyj Agree that would be a better user experience.  Productive wondering there.

**Comment by jaustin** [comment]
I'd be worried about the silent nondeterminism of dynamically limiting the number of event handlers, unless we gave some really clear user-visible warning that we were doing something 'magic' - like a "I'm full!" sign of some sort. Of course, keeping enough memory free to be able to accurately portray "I'm full but I'm still going" in an animation isn't straightforward. (I guess on the other hand you could argue that dropping packets at all is nondeterministic, so meh?)

I think my preference is for as deterministic as possible but well tuned to the circumstance. Serialising per event doesn't feel like a huge semantic change - @finneyj could you give me an example of where things might seem/feel different?

**Comment by finneyj** [comment]
I agree about the use of secret black magic - that's a line we can't cross IMHO. One of our core aims is to educate, and we can't do that if we're pulling the wool over kids eyes. Everything needs to remain deterministic.

When I say limiting the number of event handlers, I meant the number that are *serviced concurrently* at any point in time. e.g. imagine if (as int he example above) we have about 10 event handlers, and we determine (somehow!) that we can only service, say, 4 concurrently without running out of memory. We'd then service the first four that come along, and the others queue. When one of the first four completes, we round-robin across the others. I *think* this means we don't break determinism (because we don't guarantee causal ordering across event handlers - only within them). We just limit the response time a bit when things get tough. This would lead to increased queuing and "natural" loss of events as a result of course, but this seems like a more acceptable compromise for kids than a hard OOM.

If we serialize by event source, this is essentially a "static" version of the scheme described above in my mind. So take the TWSU script above - each of the event handlers attached to the same source (the DPAD) would effectively be serialized. So if one of them had long running code (say an animation that took a few seconds to complete) all the other buttons event handlers wouldn't fire in that time. Then once the animation had finished, they's all go off quickly one after the other.

I think my concern with that is the "dark side of the force" magic again. The semantics of two event handlers listening to the same source (e.g. DPAD) would be different to two event handlers listening to different sources (e.g. buttona and buttonb). That's kinda hard to explain...

(queue the star wars imperial march as Darth Jonny retires to the emperor's chamber).

**Comment by HyperDuino** [comment]
Would it be possible to have a graphic display (or at least text) of memory used by a program and its variables?  I'm now worried about the comment earlier about "it all adds up when we're running on fumes with BLE"  Just how much memory IS available once BLE is invoked? How does a user know when they've added too many blocks or variables?
