### ISSUE TITLE
Tutorial share feature

### ISSUE THREAD

**Issue by abchatra** [Microsoft/pxt#2428]
Tutorial is the only way to limit the available number of blocks. There should be a way to share the tutorial among content writers, teachers and students.

**Comment by jaustin** [comment]
@whaleygeek was telling me some primary teachers wanted to be able to limit the blocks available 'in genera' for lessons so that the younger children weren't seeing as many different items, so may be interested in this ticket.

**Comment by DavidWhaleMEF** [comment]
Oh super idea, thanks! I know @sway1233 (primary school teacher) was interested in if this was possible

**Comment by DavidWhaleMEF** [comment]
I also spoke to a number of teachers at the CASEast conference last Friday, and many of them said that they still use the 'old' BBC hosted blocks editor because it is a bit less 'overwhelming and over-packed with features' compared to makecode. This was not a criticism of makecode, more that the older BBC blocks editor had a smaller set of palettes and there was less hunting around for things - which is especially important for the younger age group where their literacy skills are perhaps not as fine tuned as the older children.

In particular, a group of primary teachers I spoke to at that event said that they would hope that either the older BBC blocks editor would remain for use in younger age primary, or that there was a suitably cut-down version of makecode that became available before the old BBC blocks editor was removed entirely. Note for @jaustin here that we should have 'simpler mode exists in makecode' as an exit criteria before the older BBC blocks editor is finally deprecated.

**Comment by abchatra** [comment]
Thanks for channeling the feedback @DavidWhaleMEF. Good reminder for all us to have a high bar for adding new UI features or categories.
