### ISSUE TITLE
Save and Download buttons

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2485]
![download_buttons](https://user-images.githubusercontent.com/5677614/28407281-79eea354-6d2b-11e7-9918-fe6596d3fe47.png)

* After the project has been named, the Save and Download buttons both download a `.hex` file when clicked - is there a difference?
* The position of the Save button implies it's a sort of OK button for after typing a new project name in the box, but we can actually rename the project without clicking on it.

**Comment by abchatra** [comment]
Save is the explicit ask from lot of teachers (We didn't have save button at the beginning). Save button is guaranteed to produce a hex file which contains source and can be reloaded in the editor. Meaning of download button might change in future, if we get an ability to flash the device directly .Even-though they do similar things, intent is different. 

This is by design.

**Comment by HelenFoster** [comment]
Maybe make this a documentation issue? If I was confused, other people might be confused too.

> Save button is guaranteed to produce a hex file which contains source and can be reloaded in the editor.

This is useful info.
