### ISSUE TITLE
Function by itself won't convert to blocks

### ISSUE THREAD

**Issue by HelenFoster** [Microsoft/pxt#2632]
If we start a new micro:bit project and write the code:
```
function f() {
    basic.pause(2000)
}
```
Then it fails to convert to blocks. Sometimes there's a red line under the pause, saying 'Language feature "basic.pause(2000)" not supported in blocks'.

Add a call to `f()` and then it converts to blocks.

Delete the `on start` block with the function call in it, convert back to JavaScript, and the code looks the same. Change something, e.g. the pause parameter, and it won't convert to blocks again.

**Comment by riknoll** [comment]
Very interesting bug! I'm pretty sure what's happening is that our compiler is optimizing away the function declaration because the function never gets called. After it is optimized away, it never passes through the compiler's emitter. The decompiler relies on the metadata generated by our emitter, so it crashes because the metadata is missing. This only affects call expressions, so this will decompile just fine:

```typescript
function f() {
    let x = 1
}
```

Solution is that we probably shouldn't do tree-shaking on user code. This isn't a decompiler bug.

**Comment by pelikhan** [comment]
This is an edge case, we should not throw tree shacking that easily.... :)

**Comment by riknoll** [comment]
I meant just for `main.ts`. Otherwise it's pretty easy to hit this bug; any function call within a function declaration that never gets called will fail to decompile.

**Comment by nielsswinkels** [comment]
Would it be possible to get a more clear error message at least? I just hit this case as well, and did not understand what was wrong.

**Comment by pelikhan** [comment]
Can we disable tree shacking when decompiling? Can this be a flag to the compiler?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
