### ISSUE TITLE
two cursors (for the price of one?)

### ISSUE THREAD

**Issue by tballmsft** [Microsoft/pxt#273]
After I add a statement, like led.plot(0,0) with intellisense, I get two cursors and typing inserts characters at both cursor positions. Interesting!

![image](https://cloud.githubusercontent.com/assets/10767146/18097934/e3b5b73c-6e94-11e6-87ae-0e2e129a118a.png)

(ignore the hexadecimal digit error message)

**Comment by microsoftsam** [comment]
This is because both parameters in this case have a default value (based on their type: number) of 0. 
We can easily fix this by updating the jsdoc for the plot function to set different default parameters. 
I could also add logic to ensure that no two parameters have the same default value. 

Now the reason that monaco assumes you want two cursors when the parameters are the same is because we wrap each of the parameters with {{VALUE}} and that in monaco goes into "parameter editing mode" (Not sure of the exact name), it just allows you to tab between parameters, then get out of that mode by pressing enter. 
It means I can type something like for, tap enter for auto completion, then edit the index variable name, and it will edit all three of them. then press tab, and edit the max value, then tab again to get inside the for loop. Enter to exit this mode. 

So it's pretty handy, the side effect is that if the two parameters have the same value, they are considered the same, and are edited with the two cursors. We can easily work around that in order to keep this feature.

**Comment by tballmsft** [comment]
Hmm, it was super confusing to me Sam.  I can't imagine what teachers/students will make of it.  We'll definitely need to discuss what Monaco features we want to expose and which we want to hide.

**Comment by microsoftsam** [comment]
Yeah absolutely, in the meantime, I'm going to remove the use of that feature for default values for parameters and snippets.
