### ISSUE TITLE
There lacks of IndexOutOfBounds Exception on array 

### ISSUE THREAD

**Issue by Helen09** [Microsoft/pxt#2774]
**Repro Steps:**
• Navigate to https://makecode.microbit.org/beta
• Drag blocks as below picture
• Change 0 to 5 on block "get value at" and observe simulator

**Expect Result:**
 There should have error message shows IndexOutOfBounds Exception
**Actual Result:**
 There didn't have any error message and simulator shows "0"
![capture](https://user-images.githubusercontent.com/23466737/29557967-4b568d80-875d-11e7-9222-73ab1a0d08d8.PNG)

**Comment by abchatra** [comment]
This is by design. We have a concept of default values, anything outside the range gives you back a default value. Zero in case of number array.
In principle this follows javascript and a conscious choice. Javascript always returns "undefined" for any out of bounds access. Errors\exceptions are usually not kid friendly
