### ISSUE TITLE
Ooops we could not load the documentation

### ISSUE THREAD

**Issue by DavidWhaleMEF** [Microsoft/pxt#2956]
parseInt() has no help, goes to a 404 page...

Actually goes here...
https://makecode.microbit.org/reference//parse-Int

But this doesn't work either.
https://makecode.microbit.org/reference/parse-Int

Reproduce by highlighting parseInt in javascript  code, right click and choose HELP from pop up menu.

**Comment by abchatra** [comment]
@ganicke Can you take a look?

**Comment by ganicke** [comment]
Looks like contextual help for built-ins is broken. Doesn't work for things like

```typescript
let tlen = "abcdef".length
let positive = Math.abs(-27)
let myInt = parseInt("35")
```

**Comment by ganicke** [comment]
Debugged this and it is due to the fact that the help path info is scraped from the line text in Monaco. So, ``parseInt()`` has no **namespace** to associate with it from the regex on the line of code. The path is missing the _/text/_ portion to complete it properly. Unfortunately, the editor context code and the block tip information aren't known to each other so the context help is just a 'guess' from the text in the JS editor.

It happens here in _editor.main.js_:

```javascript
Editor.prototype.loadReference = function () {
    Util.assert(this.editor != undefined); // Guarded
    var currentPosition = this.editor.getPosition();
    var wordInfo = this.editor.getModel().getWordAtPosition(currentPosition);
    if (!wordInfo)
        return;
    var prevWordInfo = this.editor.getModel().getWordUntilPosition(new monaco.Position(currentPosition.lineNumber, wordInfo.startColumn - 1));
    if (prevWordInfo && wordInfo) {
        var namespaceName = prevWordInfo.word.replace(/([A-Z]+)/g, "-$1");
        var methodName = wordInfo.word.replace(/([A-Z]+)/g, "-$1");
        this.parent.setSideDoc("/reference/" + namespaceName + "/" + methodName, false);
    }
    else if (wordInfo) {
        var methodName = wordInfo.word.replace(/([A-Z]+)/g, "-$1");
        this.parent.setSideDoc("/reference/" + methodName, false);
    }
};
```

Maybe @microsoftsam can comment.

**Comment by microsoftsam** [comment]
Ah yes makes sense. Thanks @ganicke. 
I can look into a fix for this. We just need to support both the case where there is a namespace and when there isn't.

**Comment by abchatra** [comment]
This is fixed.
