### ISSUE TITLE
Variable declaration messed up when switching from block to text and viceversa

### ISSUE THREAD

**Issue by tyrra** [Microsoft/pxt#3045]
### This issue regards the pxt editor (block and text) for the microbit:

When setting a value to a variable in the 'On start' block before e.g a 'Forever'-loop and then switching to textmode will have the variables declared at the top and the value 0 assigned to them. My own declarations will be done after the loop, at the bottom. 
Even if i change this in the textmode to have my values to the variables declared at the top as i wish for, switching to block and back again undo all my changes.

In block form:
![microbit-skarmbild 1](https://user-images.githubusercontent.com/1526609/30867233-b608e7c4-a2db-11e7-989c-bc19cad2f2cf.png)

When i switch to text the variables have been placed at the bottom:
<img width="630" alt="skarmavbild 2017-09-26 kl 16 55 30" src="https://user-images.githubusercontent.com/1526609/30867254-c108ecd2-a2db-11e7-9fcb-cc3ebd9a2b89.png">

I change it how i like it to be:
<img width="568" alt="skarmavbild 2017-09-26 kl 16 56 12" src="https://user-images.githubusercontent.com/1526609/30867262-c5cc6b40-a2db-11e7-88c8-29658ea70c04.png">

If i switch to block form here i get the first picture, if i then continue to switch to text again i get the second picture.

**Comment by abchatra** [comment]
Basic.forever is an event (similar to a thread or fiber) and it is designed to be before the on-start block on javascript editor. Blocks have no linear hierarchy but the javascript does. We need to choose to put the basic.forever block either before or after the javascript while converting from blocks.

We could ideally remember what user has chosen and do the same. That is a feature level change and we will evaluate. There are hard problems to solve such as what if half the on-start code is before basic.forever and rest are after.  

One change we have done today is moving basic.forever always after the on-start block code instead of before. We have observed this is the expectation of most folks .

**Comment by nielsswinkels** [comment]
The change you made with moving the forever after the onstart block, this does not have any effect yet on this issue of javascript declarations, right?

Would be really nice to get this fixed. It is one thing we have to explain in every workshop because it is confusing. My opinion would be to move all onstart code to the top of javascript. I see that as most logic because it happens first. Also it is good habit to declare variables at the top of code.

**Comment by abchatra** [comment]
This is fixed in beta. Can you verify.

**Comment by abchatra** [comment]
Sorry doesn't look like this is in beta yet.

**Comment by abchatra** [comment]
>> My opinion would be to move all onstart code to the top of javascript

@riknoll I assumed this was fixed in beta. But looks like it is not. Does this needs porting to v0?

**Comment by nielsswinkels** [comment]
I noticed a change went live today (or at least very recent), which is great! But now it is still confusing..

Now variable declaration is still highest up, and variables get their value set above the forever loop, but below any other functions (on shake, button press, custom functions, etc). So then it ends up somewhere inbetween other code, which makes it even harder to find.

**Comment by nielsswinkels** [comment]
Any thoughts on this?

**Comment by nielsswinkels** [comment]
@abchatra I'd like to bring back attention to this. Blocks in the "on start" block still end up below functions like "onButtonPressed". (see example above) Can this be changed so on start goes all the way on top in javascript mode?

**Comment by abchatra** [comment]
Today event registration is done before on-start. This is done for a reason. Students sometimes accidentally have while(true) loops in the on-start. Event registration is done as the first step to still give a reactive fidelity to students. 

Here is the order
1. Event registration first (like on button pressed etc)
2. On-start
3. Forever loop.

It is quite debatable if 1 & 2 should switch.  It is kind of hard to switch the order today as many existing programs might depend on this order.
