### ISSUE TITLE
Why are blocks layed out next to each other whereas the JS is vertical

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#3219]
I received feedback from Blocks & Beyond how the default layout of blocks changed from being layed out from left to right in Blocks to top to bottom in text. 

Since programs are written from top to bottom, can we at least change the default layout of blocks to do the same. 

<img width="395" alt="screen shot 2017-10-12 at 6 18 35 pm" src="https://user-images.githubusercontent.com/16690124/31526184-0f647040-af7a-11e7-956a-6a033372c7c1.png">

@tballmsft @Jaqster @pelikhan

**Comment by pelikhan** [comment]
Do you mean sorting the blocks to put on start on top?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
Yes

**Comment by pelikhan** [comment]
Where do you place the other handlers? Forever is special since it is registered after on start. Does it matter for kids?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by microsoftsam** [comment]
If they are all placed vertically, then the transition between blocks and text will be smoother.
and you can have a direct mapping (visually) between blocks and text. Kind of like pencil code.

**Comment by pelikhan** [comment]
I like the idea of sorting the blocks, on start, events, forever loops. On start should always be top left (or right)

The current layout tries to fill the 2D space with blocks. Thus best leveraging the available screen space so all blocks are visible at once. Going vertical only, we would loose this. Degrading the blocks experience to fit the text coding is not the way to go IMO (Pencil Code looks ugly and is not as slick and friendly as Blockly).

Instead of bending the coding experience to look more like a text editor, we should rethink the text editor to feel more like a block editor: can we have code regions colored in the text editor itself? BlueJ is an example of that https://www.bluej.org/about.html

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
