### ISSUE TITLE
support for functions in blocks editor

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#325]
Blockly support to define functions.
- [ ] add blockly blocks
- [ ] pxtarget.json flag to disable
- [ ] support for compilation to typescript
- [ ] support for decompilation from typescript
- [ ] documentation

**Comment by tballmsft** [comment]
Need to discuss about what is/isn't in Blockly from the TS side.

**Comment by abchatra** [comment]
I don't see the need for functions in blockly at this point of time. We can reevaluate on need basis. Closing this for now.

**Comment by cfscholl** [comment]
Please don't take this the wrong way but how can there be no need to learn children the foundations of programming ? Isn't this what this project is all about in the first place ? Even when programming in assembly the idea of code reuse is crucial. Are there any other blocks/concepts available so that children can learn about abstraction ?

**Comment by abchatra** [comment]
Thanks for the feedback @cfscholl. Blockly editor we target as a low entry barrier, keeping blocks to minimal. Typescript is the high ceiling and it supports all the advanced concepts including functions, classes and block scopes. Saying this, we will revisit it on going basis to evaluate the need of additional blocks.

**Comment by cfscholl** [comment]
Ok, thank you for the clarification.

**Comment by rharbird** [comment]
Hello,

I agree with @cfscholl. Writing functions is one of the first things that beginners should know. I would appreciate it if this could be reviewed. 

I teach non-computer science undergraduates and  I run robotics summer schools for 17 year olds, we use the microbit exclusively as our choice of microprocessor. The students have not programmed before and using the Blockly interface has made a huge difference to the way we are teaching. Last summer we had to teach novices C++, now there's a much lower barrier to entry - no more syntax errors! 

Thanks to the microbit and pxt we are engaging the students in some challenging projects: 

1. monitoring water usage in the college toilets and evaluating behaviour change initiatives
2. building and programming robot caterpillars (3 -4 servos) and cockroaches (4 servo motors) [https://www.flickr.com/photos/uclengineering/27560664863/in/album-72157670796148365/](bio-inspired robotics)

We're hoping that some of these will inspire kids and teachers in schools to delve deeper.

These activities require the students to write functions on day 2, we'd like to stay with the blocks-based interface to do that.

If you would like further information, let me know. 



Rae

**Comment by whaleygeek** [comment]
The problem with a blocks based function interface, is that it probably requires quite a lot of UI work to get the UX correct, as well as the technical aspects underneath it. You need to choose a function name, define parameters, and define a palette for it to live in.

I would have thought a much easier approach would be to always include a blank mycode.ts file in the project tree and ensure this always gets built into the bundle. Users could then define typescript functions in mycode.ts and apply the block annotations at the top of the function if they want them to  appear as visual blocks. These would then install ready to use visual blocks into the blocks palette and the existing UX would just work.

There may be some issues around redrawing the palette if a new function is added. But It would be a way to add user functions in-editor without any complex build or deployment steps.

The 'problem' with pxt packages, is that you have to have github access to create them (so you have to be 13 or older), and you have to get them moderated and whitelisted.

**Comment by whaleygeek** [comment]
The Ui/UX of actually designing the insides of a function using visual blocks is likely to need quite a bit of work too. So, I'm not sure it would be possible with a small amount of effort to have the whole experience in visual blocks. But you could define a bit of code in blocks, go into the TS view, cut it out and then paste it inside mycode.ts to get a visual version of that block installed in the palette. It's not a complete solution, but it would give some of the desired outcomes - abstraction and decomposition, and drawing users to be 'curious' as to what all those textual statements are really for!

**Comment by pelikhan** [comment]
Blockly has support for functions built-in.

**Comment by whaleygeek** [comment]
Related https://github.com/Microsoft/pxt/issues/882

**Comment by carlosperate** [comment]
One thing to take in consideration for functions in blockly is variable scope and the use of these new argument variable blocks inside and outside of the function block, specially taking in consideration that at the moment the variables are created globally.

**Comment by martincottrell** [comment]
Please consider a simple "macro" type subroutine. No parameters - just globals! If I can have that tomorrow thats better than nothing. I'd like parameters but macros for the block editor are necessary and needed. In fact as you cant assign a variable a pin number I can't pass those as arguments anyway so simple macros win.  Macro block that has a name.

For example lets say we have a robot with two dc motors. Lets say I use a motor controller like a 9110S with PWM input option. I want to program it in various ways. Left motor forward, right motor forward, left motor reverse, right motor reverse, left motor soft stop, right motor soft stop, left motor hard stop, right motor . I can combine those two motors in 9 different ways just counting one stop. I want the kids to program the robot to navigate a obstacle course, Now if I can define the macros for these then my main program becomes much more readable and easier to change and try out new ideas - good?

Otherwise I have to create some elaborate control frame mechanism  to keep call the main block of code with lots of ifs to execute code in another order, logical gotos! Thats a nice project but not one for them to start with perhaps.

To develop challenging scripts, extension activities, a bridge to full subroutines then something like a macro approach would be very beneficial for pupils to explore reuse and develop more complex applications more naturally.

It's not just straight computer science classes, there is a pull from DT and integrating control tech into projects, who can't do languages like TypeScript but can learn and use blocks.

Please have a think?

**Comment by gstamac** [comment]
If you look at Code Kingdoms JavaScript editor for micro:bit which is similar to pxt it supports functions with parameters. So I don't think it would be so difficult to implement it.

**Comment by AsharLohmar** [comment]
I'm new to block programming  and I also find the lack of the possibility to define functions a little "disturbing".  The only similar thing that I could find/use in order to teach my 9 years old daughter the concept of reusable code was to use the events... But it's a little off because they seem to get executed asynchronously.

**Comment by DavidWhaleMEF** [comment]
It is possible to define functions in PXT - but only in the javascript view. It does roughly round-trip back to blocks though, so here is an example of how you could do things...

First, make a little blocks program that beats a heart...

![1](https://cloud.githubusercontent.com/assets/25079586/25763793/b5ac0f7e-31dc-11e7-9ccc-b2517fd348d9.png)

Second, go into java script view to view 'under the covers'

![2](https://cloud.githubusercontent.com/assets/25079586/25763806/c16c55ee-31dc-11e7-8b85-cc02d79914bc.png)

Third, move the beating code into a beat() function with a bit of cut and paste and typing

![3](https://cloud.githubusercontent.com/assets/25079586/25763821/d1db35bc-31dc-11e7-8034-1f8731933af4.png)

Fourth, go back to blocks view and see what it has done

![4](https://cloud.githubusercontent.com/assets/25079586/25763827/da88e45c-31dc-11e7-9c79-1378098efd49.png)

Finally, use the beat() function (copy and paste) multiple times to create a bigger program, showing how a function allows reuse

![screen shot 2017-05-05 at 21 51 37](https://cloud.githubusercontent.com/assets/25079586/25763872/16440d14-31dd-11e7-818f-b91cbcb7faef.png)

**Comment by DavidWhaleMEF** [comment]
Also written up in our Knowledge-base here:

https://support.microbit.org/solution/articles/19000054480-using-functions-in-pxt

**Comment by AsharLohmar** [comment]
Yes,of course. Let's say that I was  looking for a full "block programming" experience. Maybe, if everything goes well, in a couple of weeks we will get into writing the code "by hand". My intent was just to give a "+1"/to "vote up" to the issue and give an alternative way to accomplish something similar enough .

**Comment by DavidWhaleMEF** [comment]
This is possible too, already. Although the workflow of how you get there is slightly non obvious at the moment, but it is possible:

![screen shot 2017-05-06 at 10 55 57](https://cloud.githubusercontent.com/assets/25079586/25771532/549071ce-324c-11e7-9598-3eae12078133.png)

![screen shot 2017-05-06 at 11 01 35](https://cloud.githubusercontent.com/assets/25079586/25771534/5a717520-324c-11e7-98ec-5b0099783b54.png)

As a note for @abchatra and @pelikhan if there was a right-click 'create function' option when you have a number of blocks selected (like the old 'refactor create function' that Touch Develop has, this would pretty much make the transition seamless, without having to add a whole new editor workflow. This is only an observation though, not a request. But this ticket is all about 'discussing possibilities'.

**Comment by tballmsft** [comment]
reopening as we have a good discussion going...

**Comment by abchatra** [comment]
Fixed by https://github.com/Microsoft/pxt/pull/2316

**Comment by MrVernall** [comment]
I know it's been a while since the last comment, but I just thought I'd throw my two pennies worth in. With only one 50 min lesson a week to delivery my KS3 computer science curriculum, I would be at a loss if it wasn't for block programming. I am just introducing physical computing for my year 8s and was very disappointed to see that the ability to define parameters was not available in the functions block (even in the beta). After all, this feature has been available in Scratch for years. Is this something you might reconsider for the beta - it would be very useful.

**Comment by abchatra** [comment]
@MrVernall Thanks for the feedback. We are tracking this request here: https://github.com/Microsoft/pxt-microbit/issues/689
