### ISSUE TITLE
Microbit Bluetooth LE Service Not Published

### ISSUE THREAD

**Issue by ghost** [Microsoft/pxt#3496]
Hi All,

I am trying to get the Bluetooth LE services like LED, UART or Button to work.  I was able to pair/connect/disconnect from Android phone to Microbit using Bluetooth LE.   However, I am unable to interact with the Bluetooth services.  I also used nRF to check and the services are not being publicised.

![image](https://user-images.githubusercontent.com/33738186/32923580-469f4ca0-cb73-11e7-92f7-6aa1c5709e12.png)

I read the documentation and the way to enable the Bluetooth service is to place the block in "On Start".

Did I miss out anything ?

Thanks.

ST

**Comment by abchatra** [comment]
@pelikhan any clue here?

**Comment by singkst** [comment]
Is it due to Microbit limited memory ? I did a google search and someone mentioned that the Bluetooth stack required lots of memory and that leaves little memory left to run the microbit app properly.

![microbit](https://user-images.githubusercontent.com/33738186/33105172-d365d95a-cf66-11e7-9b6d-c5429be6426a.png)
![capture](https://user-images.githubusercontent.com/33738186/33105178-d603eec2-cf66-11e7-9fc8-9e3f6e9855bc.PNG)
