### ISSUE TITLE
Bit:bot neopixel and bluetooth packages can't be installed

### ISSUE THREAD

**Issue by Dee71Miss** [Microsoft/pxt#3553]
https://makecode.microbit.org wont allow all three packages to be installed.

**Comment by abchatra** [comment]
They are not compatible due to timing issues. @jaustin Can you please elaborate?

**Comment by jaustin** [comment]
Unfortunately the Bluetooth Radio needs very precise timing and so does the Neopixel library. In order to program the neopixels we have to do disable interrupts, which means that the bluetooth stack can't guarantee it will meet the timing requirements it has. If the bluetooth stack interrupts the neopixel code, that can also cause flickering.

One workaround is to use a version of the neopixel library that allows those interruptions, but doesn't guarantee there won't be glitches in either bluetooth performance, or neopixel driving - like this one here https://github.com/LaboratoryForPlayfulComputation/pxt-neopixel-bluetoothallowed

Because that's not guaranteed to work smoothly we don't support that kind of package, I'm afraid.
