### ISSUE TITLE
Serial editor enhancement ideas

### ISSUE THREAD

**Issue by cait1inhennessy** [microsoft/pxt#3650]
## Ideas
- [x] Store more data
- [ ] Documentation
- [ ] Add timestamps to csv file
- [ ] Print out graphable data to the console: "x:123", etc
- [ ] Allow user to specify data retention limit - maybe forever
- [ ] (App) Spreadsheet should go to downloads folder
- [ ] Make new project/old data scenario less confusing
- [ ] Raw console output view/no-charts option
- [ ] Restore Azure streaming
- [ ] Minimum 5 data points and 5 ms delay before data is turned into a graph
- [ ] Label x- and y-axes on charts
- [ ] Dynamic x-axis scaling OR predetermined time length -> evenly divide x-axis
- [ ] Allow user to specify sample rate
- [ ] Have charts always take up 100% of chart area - if there are 2, 50% each, etc.
- [ ] Console area only appears if there's text output
- [ ] Permanent data viewer button instead of responsive one (app-only)
    - [ ] Then don't have recording on by default, user should have to click "start recording"
- [ ] Restore small serial preview (https://github.com/Microsoft/pxt/issues/3845)

**Comment by Jaqster** [comment]
I would also add that it's confusing to have Serial Data show up in a New Project when you have the device plugged in and running another program that's writing serial values.  I don't know if we should stop piping the data?  Or somehow make it clear this data is streaming from a live connected device, and not from anything in the current program?
<img width="413" alt="showdata" src="https://user-images.githubusercontent.com/22108954/34956211-01f63a80-f9dd-11e7-99ee-4beda13a2554.PNG">

**Comment by CarlLyman** [comment]
Apparently right now it will only keep datapoints for 20 seconds. It would be really helpful if the datapoints could last for several minutes (15-30 minutes) when you are collecting data over a longer period but only sampling it every 20-30 seconds.

It would also be nice to be able to collect data over a 24 hour period when you are only sampling the data every 10 minutes or so.

If there was a known number of datapoints that can be collected, then if there is a certain duration that is needed to collect the data, then a person could adjust the frequency of datapoint collect with the time needed to collect the sample.

**Comment by CarlLyman** [comment]
When the data is downloaded as a CSV file (data.csv) it will open generally open in a spreadsheet but where  it downloads to is not readily apparent. To find it a person needs to do a search of C:\. It is found in the following location: C:\Users\Computer Name\AppData\Local\Packages\MicrobitEducationalFounda.196216C47839B_e88r6s0b2swar\TempState
This is not an easy location to find. The program should be set to download to the "Downloads" folder where it can be found. It would be good if it created a new copy of the file, like data (1).csv, instead of just writing over the top of the previous data file.

**Comment by abchatra** [comment]
Old issue. Closing.
