### ISSUE TITLE
Can't easily get serial number that data was received from

### ISSUE THREAD

**Issue by jaustin** [Microsoft/pxt#465]
Referring to using the radio module on the micro:bit.

I can set the serial number:
![image](https://cloud.githubusercontent.com/assets/147113/19281476/6474fe3c-8fe2-11e6-848a-04581e085440.png)

But it looks like I don't have anything to "get" that at the receiving end.

I'd expect a block, perhaps like "radio receive number" or signal strenght that works inside the "on radio receive" event that gives the serial number as a number.
![image](https://cloud.githubusercontent.com/assets/147113/19281561/b356ed94-8fe2-11e6-9919-531a4060ae66.png)
^ lIke this, but "radio received serial number"

Ideally, in the event handler, the number, serial number, signal strength are all atomic for that event. (IE even if more radio data is received, while in *that* flow, the serial number is not updated, so if I store a serial number at the beginning of an event handler and a number at the end, I'm sure they are from the same packet)

**Comment by riknoll** [comment]
Having separate output blocks for each part of the packet is confusing right now. It isn't clear if using one of them "consumes" the packet or not. I think that maybe something like this might work better and be more in line with the flow bit you mentioned:

![packet](https://cloud.githubusercontent.com/assets/13754588/19325903/18e39852-907d-11e6-9b7b-90f5bc2722cc.PNG)

In that block, the variable names would work like the index in the for-loop block and be declared locally:

```typescript
radio.onPacketReceived((serial: number, signal: number, data: number) => {

});
```

We could also give the block a mutation handler to let you add/remove the parts of the packet

**Comment by pelikhan** [comment]
Yes! This is much better.

**Comment by jaustin** [comment]
Yea, I like this too - would it not be a breaking change to the radio module? That's well and good and better to make it sooner rather than later if so - might be a nice test of how we handle breaking changes to scripts.

Is there a nice trivial migration from the old mechanism to the new one?

**Comment by riknoll** [comment]
I don't know if there is an easy way to rewrite the ts code, but I spoke with @pelikhan and he suggested one option would be to keep around the old APIs and just not surface them in the block editor. That way you could still import old files and we can deprecate the APIs for eventual removal.

**Comment by riknoll** [comment]
Alright, I've been looking into this and trying to come up with a clean API for receiving packets. Here are our existing APIs for sending packets and the data that each of their packets comes with:

API                         | 1         | 2     | 3                             | 4             | 5
----------------------------|-----------|-------|-------------------------------|---------------|-------
`sendNumber(value)`         | value     | time  | serial number (*optional*)    |               |
`sendValue(value, name)`    | value     | time  | serial number (*optional*)    | name length   | name...
`sendString(string)`        | string    |       |                               |               | 

Additionally, each packet also has an rssi value available.

For `sendString()`, I think the existing `receiveString()` function is probably fine as is. If we like, we can redo it as a callback pretty easily and add the rssi, but that probably isn't necessary.

For the other two sending APIs (value and number), I think the best idea would be to have one function for both since most of the data is the same between the two. There are two ways we could do that:

## Option 1
Take a callback with a lot of optional parameters:

```typescript
radio.onPacketReceived(callback: (
    value?: number,
    name?: string,
    rssi?: number,
    time?: number,
    serial?: number
) => void): void;
```

The problem with this is that receiving just a number (i.e. sent with `sendNumber()`) is a little awkward because we have to "skip over" the name field to get the other parts of the packet. We could put the name at the end of the parameter list, but most people probably want just the value and the name so that would be even more annoying.

## Option 2

Define a `Packet` object and pass that to a callback:

```typescript
interface Packet {
    value: number;
    rssi: number;
    time: number;
    name?: string;
    serial?: number;
}

onPacketReceived(callback: (packet: Packet) => void): void;
```

I would prefer not to expose another object type in the blocks because the existing ones are already hard to wrap your head around. Instead, Instead, we can be clever when decompiling the blocks and use destructuring:

```typescript
// Justthe name and value
radio.onPacketReceived({ name, value }) => { })

// The value and some other data (with no name)
radio.onPacketReceived({ value, rssi, serial })  => { })
```

By default, we would only show two blocks in the toolbox: one that takes in a value, and one that takes a name and value. All the other "advanced" values will be hidden behind mutations that most kids can just ignore. I don't know if exposing a language feature like object destructuring would overwhelm kids, but I also don't think it is that much more magic than lambdas already are.

Thoughts?

**Comment by riknoll** [comment]
Note that for option 1, mutations would also be awkward because I don't think Blockly lets us enforce an order on the parts you can assemble. We could just figure it out during compilation, but the blocks and TS wouldn't match very cleanly.

**Comment by pelikhan** [comment]
Very elegant. I like the package interface option.

**Comment by riknoll** [comment]
Fixed with the new radio API. Some of the old APIs have been deprecated as well; old projects will still be compatible, but the old blocks no longer appear in the toolbox.
