### ISSUE TITLE
Move to the center button

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#687]
not sure the purpose of this…  I initially thought it moved your blocks together in a central part of the editor, but if my program has a bunch of different blocks spread out all over my editor, it just moves my screen to the middle.  I think what would be more helpful to line up your blocks program to the top left (like what happens when you move from JavaScript back to blocks).
[enhancement]

**Comment by microsoftsam** [comment]
This is a good idea. I was just looking into that today.
I think that would be possible, our current experience is a little jarred with where we place the blocks. Here are three scenarios where you end up with your blocks positioned in different parts of the screen: 
- Add a block, move it a little to the right (The blocks position is at X, 0)
- Reload the page, the block first appears a little to the left of its position then snaps to the right position. (I believe this is fixed with #692)
- Go to JS and back to Blocks. The block shows in the top left corner (even though its position is x,0)
- Move the workspace around, so that the block is in the middle. In this case the workspace has moved, going to JS or reloading the page, that translation is lost.  (I think this is Okay)

**Comment by pelikhan** [comment]
It is a blockly feature, we should measure if it is being used before rebuilding it.

**Comment by microsoftsam** [comment]
No longer relevant as we removed the Blockly zoom buttons.
