### ISSUE TITLE
Hidden blocks

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#688]
When blocks get hidden under other blocks, we should help the user with discoverability - maybe don't allow this at all… blocks slide to an empty space on the editor or to a program hook automatically?

**Comment by pelikhan** [comment]
When trying to snap a Bloc, it is not uncommon for children to miss the snap and overlap occurs. Moving the blocks automatically at that point might be disruptive (where did my block go).
Maybe a more prominent "Tidy up" button instead of "center view" is a better approach. Tidying would reposition and zoom in one click.

**Comment by abchatra** [comment]
Wont fix for now.
