### ISSUE TITLE
Download and Stop/Start Simulator buttons

### ISSUE THREAD

**Issue by Jaqster** [Microsoft/pxt#689]
I think we should re-think their placement.  If we have multiple micro:bits + components showing up in the simulator, these buttons get pushed all the way to the bottom.  I think it might be better to position them at the top of the simulator pane so they're always in a fixed position and always easy to find.

**Comment by tballmsft** [comment]
I also don't like that the play button is so small and never highlited/colored.

**Comment by pelikhan** [comment]
The simulator auto-restarts so we do not need that button for blocks. The stop/play button should for Javascript only.

**Comment by clowrey** [comment]
I would disagree and think the stop/play button should be on the blocks view too - while simulating music it gets super annoying with no way to stop the music playing while working on other parts of the program. Also in mobile the simulator takes up a large portion of the screen so having the option to hide/turn it off when not needed would greatly help there.

**Comment by jaustin** [comment]
I agree with @clowrey here - I think a 'stop/play' button is highly desirable for blocks. Other times when you need 'stop' in blocks aside from music (which is what drove me here) are 
* When you have simulator behaviour that causes a positive feedback loop between two micro:bits (EG a radio bridge or serial bridge)
* When you have a long program and you want to force the simulator to start at the beginning again (say, to test a different code path).

Apart from 'it's cool' - what's the reason for having the simulator always refreshing?

**Comment by pelikhan** [comment]
The blocks experience is meant to be as simple as possible and to "just work". The UI is cleaner and simpler with a single "Download" button. There is a start/stop button in JavaScript for more advanced scenarios.

For sounds, we should have a speaker icon in the simulator to turn it off (or users can simply turn it off on the computer/browser).

Kids tend to forget to restart the simulator. Restarting ensures that the simulator and code are in sync.

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by jaustin** [comment]
![image](https://cloud.githubusercontent.com/assets/147113/20648064/b9228d56-b494-11e6-868c-72ac5852a96c.png)
For muting something like this might work

But I'd really like to see a small/discrete 'simulator controls' somewhere too - even if it were just a button that moved between pause and restart (IE button shows 'pause' when simulator is running and 'restart' when it isn't)

Normal:
![image](https://cloud.githubusercontent.com/assets/147113/20648079/20212a6c-b495-11e6-9309-577f0af7440e.png)
Hover
![image](https://cloud.githubusercontent.com/assets/147113/20648083/39b4792a-b495-11e6-9ee4-fde67517f42c.png)
After pause
![image](https://cloud.githubusercontent.com/assets/147113/20648110/b64da902-b495-11e6-8b6e-bee63ab0b055.png)

(if paused the restart icon is always visible rather than dimming like it does when running)

**Comment by whaleygeek** [comment]
My comments about the auto-run semantics, matches experience I suffered with the auto-run in blocks that happened December 2015 - when running on slow laptops the auto-run behaviour makes it impossible to type text into text strings, as the browser is really busy re-running the code every time you press a key on the keyboard and change a string - if the 'auto run' could be more granular (it might be already in PXT I'm not sure) and if on by default, a 'disable' button somewhere for when on slow laptops, it is actually good because it gives a 'live coding' experience.

I agree with @jaustin point about wanting to restart the program and then test with different stimulus - I've had that issue this week when developing some resources with some kids and they said 'hey, where's the run button?'.

Finally, the computing curriculum that teachers in UK teach to, they have to talk about concepts such as editing, simulating, compiling, running - so taking out the 'run' step and making it auto-run bypasses part of the natural process and terminology they are trying to teach.

So, having it on by default, with a simple way to turn it off, I think is the best compromise all round I think, if that is possible to implement in a way that the UX looks good?

**Comment by pelikhan** [comment]
@whaleygeek this should not be the case anymore. The "old" simulator used to run within the same frame as the editor which created problems when it was hogging the CPU. In PXT, we re-architectured so that each simulator is hosted in its own iframe and does not interferre with the UI thread. If slow computers are impacted, we should detect it and automatically downgrade the aggressiveness of restart. In PXT, blocks restart is debounced to 3seconds or so. (In Touch Develop, we did some tricks to detect slow machines).

I see that there is a lot of arguments for bringing this feature under some form in the block editor. I like @jaustin suggestion but until we get it implemented,we could simply bring back that button.

@abchatra comments?

**Comment by whaleygeek** [comment]
Thanks @pelikhan that's fantastic - we get the benefits of the great 'live coding' style, without the pitfalls of sluggish slow machines - I *really* like that, thanks!

**Comment by clowrey** [comment]
I like @jaustin pause button mock-up, and would add a big red "paused" text layer over the simulator that acts as a button to reenable the simulator if you go that route. So there is really no chance to miss the fact that it is paused. 

In the long run depending on if you want to support phone sized screens you may want to add a way to hide the simulator panel entirely.

**Comment by abchatra** [comment]
@pelikhan Yes +1 for bringing back the pause button until we have a better solution. Not being able to stop music in blocks view is a compelling argument. I do like @jaustin proposal on pause button being present in the microbit simulator itself. Though we need to go through a UI design review to make sure there is no other caveats (Discoverability might be an issue).

**Comment by pelikhan** [comment]
It's back. https://github.com/Microsoft/pxt/commit/eb930048a35f11f9c64b4b077a12be34a7e93785

**Comment by abchatra** [comment]
This is fixed.
