### ISSUE TITLE
Path Following and Hitbox

### ISSUE THREAD

**Issue by Dahbix** [microsoft/pxt#7531]
Dear Makecode Team!
I am working on a game right now (Among Us) and I have a problem/request! Please add a block to the path following extension : 

(sprite) stop following (path)

Please also add a stop following player and a stop following all 

(sprite) stop following all

(sprite) stop following (sprite)

Please also add a hitbox block for example:

if distance between (sprite1) and (sprite2) is (number) do

Thanks! This would really make stuff easier to code games with enemies!
Regards 
Dahbix

**Comment by jwunderl** [comment]
Hey, thanks for the feedback!

To confirm, your referring the the tilemap path following extension (https://github.com/jwunderl/arcade-tilemap-a-star), correct? Extensions in general aren't something we can control -- as anyone can make their own -- but that does happen to be one I own so I can help! The behavior of that one should be that a sprite should stop following a path when given an empty path:

![image](https://user-images.githubusercontent.com/5615930/96355981-421c6880-109d-11eb-8fd8-71b021f7ca85.png)

or setting a speed of 0

![image](https://user-images.githubusercontent.com/5615930/96355988-611afa80-109d-11eb-84ec-2708a00b3bba.png)

however, that's broken in the past as we've had a few people work on it without having a full consensus on expected behavior. I'll test it out and make sure it works in a few minutes though -- If it's not working as expected, I'll update the extension (and describe how to get the updated extension here)

The same is true for the sprite follow block -- passing 0 or a nonexistent sprite will clear them.

I suppose we could consider having a way internally for extensions / etc to register a sprite as following something, and use that to provide a block to dismiss all at once -- will have to think about how that would look a bit.

For the last portion - a block to calculate distance between sprites - but do you have an example of a use case I could look over? I would imagine we could make a quick extension that has a few common functions between sprites -- `angle between sprite1 and sprite2`, `distance between sprite1 and sprite2`, etc - but would possibly have to think a little more on exactly what those thing means - e.g. in this case it looks like you're requesting `how far away are they before they would be counted as overlapping`, which is much more complicated to get exactly right

**Comment by jwunderl** [comment]
Oh, also made a quick extension with some helpers / blocks I'd been wanting, including a block for distance between two sprites: https://github.com/jwunderl/arcade-sprite-util There should be help docs for each block in case anything isn't clear. If you did want it to be hitbox based I can add another block for something like that (the distance block in there is based off the center of the sprites, to be consistent with the other blocks we have / useful with the angle block)

**Comment by Dahbix** [comment]
Thank you a lot! I want to use the distance between 2 sprites for this:
Kill Range ( Not having to overlat to kill) (works perfectly fine)

There is red (me) and green (enemy). Green is the killer. If I am in a certain radius then Green should follow me. If not he should follow his path. But here is the problem: He does follow me when I am in range and he stops following me when I am not in range, but he just stops and does not follow his path... 
This is the code piece (path is already set)
![image](https://user-images.githubusercontent.com/73031484/96608301-8015c880-12f9-11eb-8fa7-82f91a4a264e.png)
Hope you can help me
Thanks!!
