### ISSUE TITLE
Erratic commenting behaviour

### ISSUE THREAD

**Issue by whaleygeek** [Microsoft/pxt#778]
microbit.org-ticket: 298
pxt.microbit.org version: 0.6.13

I'm struggling to make any sense of commenting in PXT. Here is a workflow that shows comments getting deleted, comments getting turned from multi-line into single line, and comments not displaying properly in the GUI

![screen shot 2016-11-15 at 22 33 14](https://cloud.githubusercontent.com/assets/4086785/20327245/3edac914-ab84-11e6-9ec6-ce828de29d76.png)

![screen shot 2016-11-15 at 22 33 21](https://cloud.githubusercontent.com/assets/4086785/20327248/42aca918-ab84-11e6-8fc7-485559cab07f.png)

![screen shot 2016-11-15 at 22 33 36](https://cloud.githubusercontent.com/assets/4086785/20327260/4acc2a38-ab84-11e6-9294-8be66c64cfde.png)

![screen shot 2016-11-15 at 22 33 43](https://cloud.githubusercontent.com/assets/4086785/20327267/4de6386c-ab84-11e6-95e4-fe6d9fd6ca1b.png)

![screen shot 2016-11-15 at 22 33 48](https://cloud.githubusercontent.com/assets/4086785/20327272/51ce59fa-ab84-11e6-9e40-f674734d5944.png)

![screen shot 2016-11-15 at 22 35 40](https://cloud.githubusercontent.com/assets/4086785/20327283/55b17c8c-ab84-11e6-813e-e4464f371225.png)

![screen shot 2016-11-15 at 22 35 46](https://cloud.githubusercontent.com/assets/4086785/20327287/599bbbf0-ab84-11e6-91d3-e1c38c8037ab.png)

![screen shot 2016-11-15 at 22 35 52](https://cloud.githubusercontent.com/assets/4086785/20327291/5c4d0a0c-ab84-11e6-8de0-c980cdf0ef83.png)

**Comment by whaleygeek** [comment]
Just a note, we also had this reported about comments sometimes causing the compile process to freeze, adding it here in case it is related:

_I have now found that If I collapse the comment before compiling, the process goes through its normal sequence. It is only if the comment is left open when the compile is called that the screen freezes_

**Comment by riknoll** [comment]
The second issue is actually unrelated to the first, so I'm going to make a new issues for it.

**Comment by riknoll** [comment]
See #793

**Comment by riknoll** [comment]
The first looks like a pretty bad UI bug, and if you have steps to reproduce, I would appreciate it.

I agree that comments are pretty weird right now; the issue is that comments are pretty difficult for us to roundtrip correctly. We don't have a mechanism for keeping metadata between blocks and JS. That includes whether a comment is supposed to be a single-line comment or multi-line, so we made the conscious decision to convert all comments from Blockly to single-line style comments that are word-wrapped. That is also the reason your multi-line comment lost its line breaks; it was treated as word-wrapped paragraph and the line breaks got removed in the round trip. If you want to have line breaks in your comment, you can leave a blank line in between the paragraphs.

As for comments disappearing, comments should be grouped to the block that is directly below them. In your example, there isn't a block to add the comment to and so we just remove it. We should probably refuse to decompile if there is a comment that would be deleted.

**Comment by pelikhan** [comment]
We should flag when we are unable to decompile a comment.

**Comment by whaleygeek** [comment]
@pelikhan @riknoll I know you have done a lot in the new Beta to look into this, but I'm struggling to find the necessary updates and tickets that relate to this. Could you link them to this ticket so I can find my way here, or update this ticket with where we are with fixing this bug? Steps to reproduce are at the start of this ticket, thanks.

**Comment by HelenFoster** [comment]
@riknoll

> We don't have a mechanism for keeping metadata between blocks and JS. That includes whether a comment is supposed to be a single-line comment or multi-line, so we made the conscious decision to convert all comments from Blockly to single-line style comments that are word-wrapped. That is also the reason your multi-line comment lost its line breaks; it was treated as word-wrapped paragraph and the line breaks got removed in the round trip. If you want to have line breaks in your comment, you can leave a blank line in between the paragraphs.

You don't have a mechanism to store whether a comment was `//` or `/*`, but that's of much less importance.

Why not preserve line breaks anyway? I found the current behaviour unexpected and frustrating. (And if someone has commented out code, it gets broken.)

**Comment by pelikhan** [comment]
@riknoll did you have to take another look here?

**Comment by abchatra** [comment]
Closing old issues. If this is still an issue please reopen.
