### ISSUE TITLE
pourriez vous m'aider svp

### ISSUE THREAD

**Issue by skipy57** [microsoft/pxt#7897]
![image](https://user-images.githubusercontent.com/79223196/108255586-c15d9e00-715c-11eb-86a7-4193fcaf794c.png)

**Comment by jwunderl** [comment]
@skipy57 this is a bug that was fixed in the last release (`v3.0.65`). If you download a new version from https://makecode.microbit.org/offline-app it should not run into this issue anymore. This one likely won't happen consistently / if you try and reopen a few times it likely will handle the update successfully and not run into this issue anymore.

Sorry for the trouble!

**Comment by abchatra** [comment]
fixed
