### ISSUE TITLE
User Feedback: Download instructions

### ISSUE THREAD

**Issue by samelhusseini** [Microsoft/pxt#888]
Download instructions contains a lot of text. Kids don't like reading text. 

Let's create browser specific gifts / videos to show the process of downloading and copying the hex file onto the device.

**Comment by jaustin** [comment]
Could we also have a 'never show this to me again' button please?

**Comment by pelikhan** [comment]
We could have that for the current session but it would not be stored so that the next student on the machine gets it.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jaustin** [comment]
For current session is good enough for now -  though could it also be stored in the current project?/HTML5 local storage? Do you store anything there except code currently?

**Comment by EdNutting** [comment]
Only per session, then it doesn't matter if laptops get used in different lessons with different kids. 

Videos are fraught with problems because of school blocking systems. Gifs are a good idea but will be hampered by OS specificity and how the machine has been set up. As it is, even with Gifs for the specific setup, I still have to walk a class through how to do it at the start of each session, then again later in the session and with some children individually. Children these days don't understand file systems or how to save stuff other than in the downloads folder. I wouldn't waste too much time trying to make the Microbit editor tackle this problem.

Just having a box that says "Well done! You downloaded your program. Did you save it to the Microbit or your computer? Ask your teacher if you're unsure." would be more HELPFUL IMHO with a button to say "show detailed instructions" (for use mainly by teachers if they forget what to do or are new to the editor).

**Comment by pelikhan** [comment]
Unfortunately right. Same experience here with US students: they struggle with basic file operation.

Note: same experience when training teachers as well, many teachers unable to perform the D&D operation.

**Comment by jaustin** [comment]
If GIF/Video doesn't work, can we use JS to do a little animation of a file being dragged (OS-specific) and even 'train' them based on their platform and some canned images of Explorer/Finder? Like, drag this item (arrow points at the hex file) to here (arrow points at the MICROBIT drive).

I used to use a slide where I animated this based on a screenshot and it helped quite a lot. 

J

**Comment by EdNutting** [comment]
GIF would work but the animations need careful thought. For example, my GIFs were thwarted by one school were in Windows Explorer "Computer" was collapsed by default and opening it showed Microbit on a strange drive letter. Some kids don't pay attention to the details so get over this bit fine but then struggle to code. Those who understand details matter in code get stuck with saving files because the drive letter, layout, whatever else, doesn't quite match the screen shots. It's a lose-lose situation on that front. 

I still think a simple message as suggested would be best. It allows the teacher to easily take control of that part of teaching for whatever environment they're working in.

**Comment by abchatra** [comment]
Closing old issues. If this is still an issue please reopen.
