### ISSUE TITLE
refactor built-in blocks to support localization

### ISSUE THREAD

**Issue by pelikhan** [Microsoft/pxt#99]
currently, math/loops/text/etc... are not localizable

**Comment by sgk** [comment]
Currently, some blocks under Loops, Logic, Variables and Math have localized field strings which are derived from the localization feature of Blockly. How do you think you will continue to use the localization feature of Blockly, or use your own `lf()` mechanism?

I hope you to choose to use your own localization mechanism throughout your project.

For Japanese language, the localized strings from Blockly are awful and sometimes incorrect, which are a little bit hard to understand for children and even adults. It is better if we can contribute to the Blockly project itself to have fluent localized strings, but it should be very hard and time consuming because the work will include changes to the source code not only the localization strings file.

Another reason is target age of children. For example, 12 years old children (6th grade in elementary school) know about 1000 characters and 20000 words while adults know about 5000 characters and 50000 words. If the localized strings are natural to adults, it cannot be understood by children. We have to choose right characters and words carefully when translating the strings. If we continue to use Blockly's own localization strings for the builtin blocks, the resulting product will be inconsistent in its human language.

Here is my trial to translate blocks under Loops category. It is very far from complete.
https://github.com/sgk/pxt/commit/92c59be

**Comment by pelikhan** [comment]
Good point. Yes, we want to control the quality of our translations.

**Comment by sgk** [comment]
Thank you. I am relieved to hear that. I will show you my trial to add natural translation as a pull request when it become certain level.

**Comment by riknoll** [comment]
Is there anything left to be done on this issue? Or are all of the builtin blocks now covered [in blocklyloader.ts](https://github.com/Microsoft/pxt/blob/master/pxtblocks/blocklyloader.ts#L529)?

**Comment by pelikhan** [comment]
Anything in index.html should be refactored.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________
